name: my_desktop_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3+1
  path: ^1.9.0
  image_picker: ^1.1.2
  # This is necessary for image_picker on Windows/Linux (keep it)
  flutter_plugin_android_lifecycle: ^2.0.17
  google_fonts: ^6.2.1
  provider: ^6.1.2
  path_provider: ^2.1.5
  audioplayers: ^6.5.0
  shared_preferences: ^2.5.3
  flutter_barcode_scanner: ^2.0.0
  
  # New dependencies for PDF generation
  pdf: ^3.10.8
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # To add assets (images, fonts, etc.) to your application, add an assets section here.
  assets:
    - assets/pet_shop_icon.png
    # You can also uncomment the line below to include all images from the 'assets' folder
    # - assets/